# Generated by Django 5.2.8 on 2025-11-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('approve', 'Approve'), ('finance', 'Finance')], default='staff', max_length=20),
        ),
    ]
