# Generated by Django 5.2.8 on 2025-11-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('approve', 'Approver'), ('finance', 'Finance')], default='staff', max_length=20),
        ),
    ]
