# Generated by Django 5.2.8 on 2025-11-25 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='proforma',
            field=models.FileField(blank=True, null=True, upload_to='proformas/'),
        ),
        migrations.AddField(
            model_name='request',
            name='purchase_order',
            field=models.FileField(blank=True, null=True, upload_to='purchase_orders/'),
        ),
        migrations.AddField(
            model_name='request',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
