# Generated by Django 5.2.8 on 2025-11-26 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_request_payment_date_request_payment_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='finance_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_uploaded_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RECEIPT_UPLOADED', 'Receipt Uploaded'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
    ]
